### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Waterdrips**

### CODE REVIEW

**Comment by Waterdrips** [comment]
> I think this should be accompanied by an automated test
 
@Amyliorate - iv written the test - just need @AndyMacDroo to add some ops for his dev...

**Comment by Amyliorate** [comment]
Thanks @Waterdrips

**Comment by Datedsandwich** [comment]
@Amyliorate please approve if you're happy with this

**Comment by cpettifer** [comment]
> :amy:

fix this please

**Comment by AndyMacDroo** [comment]
Thanks @Waterdrips, this looks great! 👍

**Comment by AndyMacdonaldELS** [comment]
@lukebrowne @Amyliorate @Datedsandwich @cpettifer 

👋 Hello!

**Comment by AndyMacDroo** [comment]
@Datedsandwich @Amyliorate @lukebrowne @cpettifer 








... 👋 Hello!

**Comment by cpettifer** [comment]
👋

**Comment by Datedsandwich** [comment]
👋 go team!

**Pull request merged**
